language: generic
sudo: required
osx_image: xcode8
script:
      - swift package generate-xcodeproj
          - xcodebuild -scheme RequestBuilder -enableCodeCoverage YES test  # instead of swift test
after_success:
      - bash <(curl -s https://codecov.io/bash)
